---
name: Telethon to Home Assistant
version: 1.0.0
slug: telethon2sensor
description: Telegram chatbot messages listener for Home Assistant
url: https://github.com/semitop7/ha-sensor-telethon
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/semitop7/{arch}-addon-telethon2sensor
homeassistant_api: true
usb: true
map:
  - share:rw
  - addons
init: false
options:
  api_id: ""
  api_hash: ""
  chat_bot_username: ""
  debug: false
schema:
  api_id: str
  api_hash: str
  chat_bot_username: str
  debug: bool